fetch_comments_task:
  description: >
    Retrieve all comments for the specified video ID {video_id}, ensuring data integrity and relevance.
  expected_output: >
    A JSON formatted list of all retrieved comments for video ID {video_id}, 
    with each entry clearly annotated and relevant to the context of the video.

insights_task:
  description: >
    Analyze the retrieved comments to distill actionable insights for video ID {video_id}, 
    identifying key themes and potential improvements.
  expected_output: >
    A structured JSON document containing categorized insights such as 'Requests', 'Complaints', 'Praise', and 'Suggestions', 
    each supported by specific examples from the comments.

reporting_task:
  description: >
    Compile a detailed report from the insights gathered, structured to guide content enhancement for video ID {video_id}. 
    Include comprehensive sections supported by cited comments.
  expected_output: >
    In the Introduction include the full url of the video_id
    A detailed and well-organized markdown report with sections dedicated to each theme identified in the insights phase. 
    Each section should include citations from the comments to support claims, with a focus on clarity and actionability.
